# Generated by Django 4.2.5 on 2023-12-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(1, 'Ожидание'), (2, 'В процессе'), (3, 'Выполнено')], default=1)),
            ],
        ),
    ]
